[font]
# Normal font face
normal = { family = "BlexMono NerdFont", style = "Regular" }
# Bold font face
bold = { family = "BlexMono NerdFont", style = "Bold" }
# Italic font face
italic = { family = "BlexMono NerdFont", style = "Italic" }
# Font size
size = 12.5


[colors.normal]
black   = '#3F3F3F'
red     = '#705050'
green   = '#60B48A'
yellow  = '#DFAF8F'
blue    = '#9AB8D7'
magenta = '#DC8CC3'
cyan    = '#8CD0D3'
white   = '#DCDCCC'

# Bright colors
[colors.bright]
black   = '#709080'
red     = '#DCA3A3'
green   = '#72D5A3'
yellow  = '#F0DFAF'
blue    = '#94BFF3'
magenta = '#EC93D3'
cyan    = '#93E0E3'
white   = '#FFFFFF'
