--vim.wo.number = true
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.mouse = 'a'
vim.wo.signcolumn = 'yes'
--tabs & indentations
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.backspace = "indent,eol,start"
vim.opt.autoindent = true
vim.opt.wrap = false
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.cursorline = true
vim.opt.splitbelow = true
--FOR WINDOWS
--vim.opt.shell = "powershell.exe"
